branches:
  only:
    - master

language: bash

services:
  - docker

env:
  global:
    - AGENT=
    - TAG=

matrix:
  include:
    - env: AGENT=php
           TAG=7.2
    - env: AGENT=php
           TAG=7.3

before_install:
  - cd "${AGENT}/${TAG}"

script:
  - docker build --tag="core23/jenkins-${AGENT}-agent:${TAG}" .

after_script:
  - docker images
