branches:
  only:
    - master

language: bash

services:
  - docker

env:
  global:
    - AGENT=
    - TAG=

matrix:
  include:
    - env: AGENT=php
           TAG=7.2
    - env: AGENT=php
           TAG=7.3
    - env: AGENT=php
           TAG=7.4
script:
  - make ${AGENT}-${TAG}

after_script:
  - docker images
