on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  push:
    branches:
      - "**"
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  test:
    name: "Docker Compose"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v1"

      - name: "Build the stack"
        run: "docker-compose build"

      - name: "Show images"
        run: "docker-compose images"
