name: 'Continuous Integration'

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-build:
    name: "Build ${{ matrix.php-version }}-${{ matrix.base-image }}"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.0"
          - "8.1"

        base-image:
          - "alpine"
          - "debian"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Build"
        run: "DOCKER_BUILDKIT=1 docker build php/${{ matrix.base-image }}/${{ matrix.php-version }} -t ghcr.io/core23/jenkins-php-agent:${{ matrix.php-version }}-${{ matrix.base-image }}"

      - name: "History"
        run: "docker image history ghcr.io/core23/jenkins-php-agent:${{ matrix.php-version }}-${{ matrix.base-image }}"

      - name: "Size"
        run: "docker images ghcr.io/core23/jenkins-php-agent:${{ matrix.php-version }}-${{ matrix.base-image }} --format \"{{.Repository}}:{{.Tag}} -> {{.Size}}\""

      - name: "Show version"
        run: "docker run --rm --entrypoint sh ghcr.io/core23/jenkins-php-agent:${{ matrix.php-version }}-${{ matrix.base-image }} php --version"
