on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  push:
    branches:
      - "**"
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  test:
    name: "Test"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        image:
          - agent-php71
          - agent-php72
          - agent-php73
          - agent-php74

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.3"

      - name: "Build"
        run: "docker-compose build ${{ matrix.image }}"
