# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
    push:
      - "**"
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  test:
    name: "Docker Compose"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build the stack
        run: docker-compose up -d

      - name: Test
        run: |
          docker-compose version
          docker-compose up -d --force-recreate
          curl http://localhost:$(docker-compose port nginx 80 | cut -d ":" -f 2)
