name: "Build and push containers"

on:
  schedule:
    - cron: '31 19 * * *'
  push:
    branches: [ main ]

jobs:
  release-container:
    name: "Push Docker image to GitHub Packages"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

        base-image:
          - "alpine"
          - "debian"

        exclude:
          - php-version: "8.1"
            base-image: "alpine"
          - php-version: "7.4"
            base-image: "debian"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Docker meta"
        id: "meta"
        uses: "docker/metadata-action@v3"
        with:
          flavor: |
            latest=false
          images: |
            core23/jenkins-php-agent
            ghcr.io/core23/jenkins-php-agent
          tags: |
            type=raw,value=${{ matrix.php-version }}-${{ matrix.base-image }}
            type=raw,value=${{ matrix.php-version }},enable=${{ startsWith(matrix.base-image, 'debian') }}

      - name: "Setup QEMU"
        uses: "docker/setup-qemu-action@v1"

      - name: "Setup Docker Buildx"
        uses: "docker/setup-buildx-action@v1"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_GH_USERNAME }}
          password: ${{ secrets.CONTAINER_GH_PAT }}

      - name: "Login to DockerHub Registry"
        uses: "docker/login-action@v1"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push"
        uses: "docker/build-push-action@v2"
        with:
          context: "php/${{ matrix.base-image }}/${{ matrix.php-version }}"
          platforms: "linux/amd64"
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
