name: Build and push containers

on:
  schedule:
    - cron: '31 19 * * *'
  push:
    branches: [ main ]

jobs:
  release-container:
    name: "Push Docker image to GitHub Packages"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup QEMU"
        uses: "docker/setup-qemu-action@v1"

      - name: "Setup Docker Buildx"
        uses: "docker/setup-buildx-action@v1"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_GH_USERNAME }}
          password: ${{ secrets.CONTAINER_GH_PAT }}

      - name: "Build and push"
        uses: "docker/build-push-action@v2"
        with:
          context: .
          file: ./php/${{ matrix.php-version }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: "ghcr.io/core23/jenkins-php-agent:${{ matrix.php-version }}"
